# Generated by Django 5.2.3 on 2025-06-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroservicios',
            name='barbero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicios', to='usuarios.barbero'),
        ),
        migrations.AddField(
            model_name='registroservicios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroservicios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_servicios', to='servicios.servicio'),
        ),
    ]
