# Generated by Django 5.2.6 on 2025-11-08 00:48

import django.db.models.deletion
import django.utils.timezone
import utils.binary_excel_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('tipo_archivo', models.CharField(choices=[('individual', 'Archivo Individual'), ('historial', 'Historial Maestro')], default='individual', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del contenido del archivo')),
                ('archivo_excel', utils.binary_excel_fields.BinaryExcelField(blank=True, help_text='Archivo Excel almacenado en base64', null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_periodo_inicio', models.DateField(blank=True, help_text='Fecha de inicio del período archivado', null=True)),
                ('fecha_periodo_fin', models.DateField(blank=True, help_text='Fecha de fin del período archivado', null=True)),
                ('cantidad_turnos', models.PositiveIntegerField(default=0, help_text='Cantidad de turnos archivados en este archivo')),
                ('tamaño_bytes', models.PositiveIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('version', models.CharField(default='1.0', help_text='Versión del archivo', max_length=20)),
                ('archivo_padre', models.ForeignKey(blank=True, help_text='Archivo del cual deriva este (para historial)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.archivoexcel')),
            ],
            options={
                'verbose_name': 'Archivo Excel',
                'verbose_name_plural': 'Archivos Excel',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='administrac_fecha_c_2537b5_idx'), models.Index(fields=['tipo_archivo'], name='administrac_tipo_ar_d9d321_idx'), models.Index(fields=['fecha_periodo_inicio', 'fecha_periodo_fin'], name='administrac_fecha_p_5fb6e6_idx')],
            },
        ),
    ]
