# Generated by Django 5.2.6 on 2025-11-08 01:15

import django.utils.timezone
import utils.binary_excel_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_archivoexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del backup', max_length=255)),
                ('tipo_backup', models.CharField(choices=[('json', 'JSON (Fixtures)'), ('sqlite', 'SQLite (Base de datos)'), ('completo', 'Completo (ZIP)')], default='completo', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del backup')),
                ('archivo_backup', utils.binary_excel_fields.BinaryExcelField(blank=True, help_text='Archivo de backup almacenado en base64', null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('tamaño_bytes', models.PositiveIntegerField(default=0, help_text='Tamaño del archivo en bytes')),
                ('incluye_media', models.BooleanField(default=False, help_text='Si incluye archivos media')),
                ('version_django', models.CharField(blank=True, help_text='Versión de Django', max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el backup')),
                ('creado_automaticamente', models.BooleanField(default=False, help_text='Si fue creado automáticamente')),
            ],
            options={
                'verbose_name': 'Backup de Base de Datos',
                'verbose_name_plural': 'Backups de Base de Datos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='administrac_fecha_c_4d4ccf_idx'), models.Index(fields=['tipo_backup'], name='administrac_tipo_ba_9a3d18_idx')],
            },
        ),
    ]
