# Generated by Django 5.2.6 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_backupbasedatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupbasedatos',
            name='tipo_backup',
            field=models.CharField(choices=[('json', 'JSON (Fixtures)'), ('sqlite', 'SQLite (Base de datos)'), ('full', 'Completo (ZIP)')], default='full', max_length=20),
        ),
    ]
