# Generated by Django 5.2.6 on 2025-11-07 23:21

import utils.image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_inscripcioncurso_curso_inscriptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=utils.image_fields.CursoImageField(blank=True, null=True, upload_to='cursos/'),
        ),
    ]
