# Generated by Django 5.2.6 on 2025-11-07 23:38

import utils.binary_image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=utils.binary_image_fields.CursoBinaryImageField(blank=True, max_length=2000000, null=True),
        ),
    ]
