# Generated by Django 5.2.6 on 2025-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-dia', '-hora']},
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, max_length=2000000, null=True),
        ),
    ]
