# Generated by Django 5.2.6 on 2025-11-07 23:38

import utils.binary_image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=utils.binary_image_fields.ServicioBinaryImageField(blank=True, max_length=2000000, null=True),
        ),
    ]
