# Generated by Django 5.2.6 on 2025-09-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio final del turno (puede ser diferente al precio del servicio)', max_digits=10, null=True),
        ),
    ]
