# Generated by Django 5.2.6 on 2025-09-30 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('turnos', '0004_turno_precio_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicios.servicio'),
        ),
    ]
