# Generated by Django 5.2.6 on 2025-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_turno_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('cancelado', 'Cancelado'), ('completado', 'Completado'), ('expirado', 'Expirado')], default='disponible', max_length=20),
        ),
    ]
