"""
Django settings for BarberiaApp project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar entorno
env = environ.Env(
    DEBUG=(bool, False)
)

# Intentar cargar .env file (para desarrollo local)
try:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
except:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', env('SECRET_KEY', default='django-insecure-fallback-key'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else env('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Para servir archivos estáticos en producción
    'cloudinary_storage',  # Debe ir antes de staticfiles
    'cloudinary',
    'rest_framework',
    'rest_framework_simplejwt',
    'usuarios',
    'turnos',
    'servicios.apps.ServiciosConfig',
    'administracion',
    'productos',
    'BarberiaApp.apps.BarberiaappConfig',
    'cursos',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para archivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BarberiaApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BarberiaApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Usar SQLite tanto en desarrollo como en producción para evitar problemas con psycopg2
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'usuarios.Usuario'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Cordoba'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Archivos estáticos de la aplicación (logos, imágenes por defecto)
]

# Configuración de WhiteNoise para servir archivos estáticos Y media
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_URL y MEDIA_ROOT se configuran dinámicamente más abajo según Cloudinary

# Configurar WhiteNoise para servir archivos media
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Directorio base para media (se usa si no hay Cloudinary)
MEDIA_ROOT = BASE_DIR / 'media'
WHITENOISE_ROOT = MEDIA_ROOT

# Configuraciones adicionales para producción
if not DEBUG:
    # Configuraciones de seguridad para producción
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Configuración de archivos media - ALMACENAMIENTO LOCAL OPTIMIZADO
# Sistema de imágenes optimizadas con conversión automática a WebP

# Configuración de almacenamiento local
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Crear directorios de media si no existen
MEDIA_DIRS = ['perfiles', 'productos', 'barberos', 'servicios', 'cursos', 'carousel']
for media_dir in MEDIA_DIRS:
    dir_path = os.path.join(MEDIA_ROOT, media_dir)
    os.makedirs(dir_path, exist_ok=True)

# Configuración para el sistema de optimización de imágenes
IMAGE_OPTIMIZATION = {
    'ENABLED': True,
    'FORMAT': 'WEBP',  # Formato de salida
    'QUALITY': {
        'perfil': 85,
        'producto': 80,
        'barbero': 85,
        'servicio': 80,
        'curso': 80,
        'default': 80
    },
    'SIZES': {
        'perfil': {'width': 400, 'height': 400},
        'producto': {'width': 800, 'height': 600},
        'barbero': {'width': 600, 'height': 600},
        'servicio': {'width': 800, 'height': 500},
        'curso': {'width': 1000, 'height': 600},
        'default': {'width': 800, 'height': 600}
    }
}

# Configuración de Cloudinary
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Configuración de Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Configurar cloudinary
cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key=CLOUDINARY_STORAGE['API_KEY'],
    api_secret=CLOUDINARY_STORAGE['API_SECRET'],
)

# Configuración de STORAGES para Django 4.2+
if all([CLOUDINARY_STORAGE['CLOUD_NAME'], CLOUDINARY_STORAGE['API_KEY'], CLOUDINARY_STORAGE['API_SECRET']]):
    # Usar Cloudinary como storage por defecto para archivos media
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    
    print("✅ Cloudinary configurado como storage backend")
    print(f"✅ Cloud Name: {CLOUDINARY_STORAGE['CLOUD_NAME']}")
else:
    # Fallback a almacenamiento local si Cloudinary no está configurado
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    print("⚠️ Cloudinary no configurado, usando almacenamiento local")

print("✅ Sistema de imágenes optimizadas configurado")
print(f"✅ Directorio media: {MEDIA_ROOT}")
print(f"✅ URL media: {MEDIA_URL}")
print("✅ Conversión automática a WebP habilitada")

LOGOUT_REDIRECT_URL = '/'
