# Generated by Django 5.2.3 on 2025-08-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carousel/')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
