# Generated by Django 5.2.6 on 2025-11-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarberiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='imagen',
            field=models.ImageField(upload_to='carousel/'),
        ),
    ]
