# Generated by Django 5.2.6 on 2025-11-07 23:21

import utils.image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarberiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='imagen',
            field=utils.image_fields.OptimizedImageField(upload_to='carousel/'),
        ),
    ]
