# Generated by Django 5.2.3 on 2025-06-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_trabajobarbero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajobarbero',
            name='descripcion',
        ),
    ]
