# Generated by Django 5.2.3 on 2025-06-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_trabajobarbero_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbero',
            name='redes',
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='usuarios.barbero')),
            ],
        ),
    ]
