# Generated by Django 5.2.3 on 2025-06-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_barbero_redes_redsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocial',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
