# Generated by Django 5.2.3 on 2025-09-24 20:09

from django.db import migrations

def set_default_profile_images(apps, schema_editor):
    """Asigna imagen por defecto a usuarios sin foto de perfil"""
    Usuario = apps.get_model('usuarios', 'Usuario')
    # No es necesario hacer nada aquí, porque el método get_foto_perfil_url() 
    # maneja automáticamente los casos donde foto_perfil es None o vacío

def reverse_default_profile_images(apps, schema_editor):
    """Función reversa - no hace nada ya que no modificamos los datos"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_is_active'),
    ]

    operations = [
        migrations.RunPython(
            set_default_profile_images,
            reverse_default_profile_images
        ),
    ]
