# Generated by Django 5.2.6 on 2025-11-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20250924_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='barberos/'),
        ),
        migrations.AlterField(
            model_name='trabajobarbero',
            name='imagen',
            field=models.ImageField(upload_to='barberos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
