# Generated by Django 5.2.6 on 2025-11-07 23:38

import utils.binary_image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_barbero_foto_alter_trabajobarbero_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbero',
            name='foto',
            field=utils.binary_image_fields.BarberoBinaryImageField(blank=True, max_length=2000000, null=True),
        ),
        migrations.AlterField(
            model_name='trabajobarbero',
            name='imagen',
            field=utils.binary_image_fields.BarberoBinaryImageField(max_length=2000000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=utils.binary_image_fields.PerfilBinaryImageField(blank=True, max_length=2000000, null=True),
        ),
    ]
