# Generated by Django 5.2.6 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_barbero_foto_alter_trabajobarbero_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbero',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='barbero',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página (menor número = aparece primero)'),
        ),
    ]
