# Generated by Django 5.2.6 on 2025-11-07 23:21

import utils.image_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=utils.image_fields.ProductoImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
