# Generated by Django 5.2.6 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición en la página (menor número = aparece primero)'),
        ),
    ]
